### ISSUE TITLE
Support integration tests

### ISSUE THREAD

**Issue by josteinaj** [daisy/xproc-maven-plugin#7]
The idea would be that all the dependencies (i.e. other modules) would be fetched and unzipped. All the module dependencies in the XML catalogs should be resolved to their path on the filesystem (according to their Maven coordinates?). For instance:

``` xml
<nextCatalog catalog="org:daisy:pipeline:modules:common-utils"/>
```

...would become something like...

``` xml
<nextCatalog catalog="file:/tmp/it/repo/org/daisy/pipeline/modules/common-utils/META-INF/catalog.xml"/>
```

wdyt?

**Comment by bertfrees** [comment]
Shall we close this?

**Comment by josteinaj** [comment]
Probably. Is the `<nextCatalog ...>` things still required?
